#! /bin/bash

# Copies the .bashrc, .vimrc, and the .vim folder to this directory, then adds
# them to git, commits them, pushes to the remote repository, and deletes the
# files in order to save space. This script is only meant to be used in the
# repository directory.

cp ~/.bashrc ~/.bash_aliases ~/.rtorrent.rc ~/.vimrc ~/.dircolors ~/.screenrc .
cp -r ~/.vim .

git add .bashrc .vimrc .vim copypush .dircolors .screenrc

date=$(date)
printf "Commit message: "
read message
git commit -am "Commit on $date; message: $message"

git push origin master

rm .bashrc .vimrc .bash_aliases .rtorrent.rc .screenrc .dircolors
rm -r .vim
