#! /bin/bash

# Copies the .bashrc, .vimrc, and the .vim folder to this directory, then adds
# them to git, commits them, pushes to the remote repository. This script is
# only meant to be used in the repository directory.

cp ~/.bashrc ~/.bash_aliases ~/.rtorrent.rc ~/.vimrc ~/.dircolors ~/.screenrc .tmux.conf .
cp -r ~/.vim .

git add .bashrc .vimrc .vim copypush pushdelete .dircolors .screenrc

branch="master"

if [[ $# > 0 ]]; then
    branch=$1
fi

date=$(date)
printf "Commit message: "
read message
git commit -am "Commit on $date; message: $message"

git push origin $branch
